# https://starship.rs/config/#prompt
# Fonts: https://github.com/ryanoasis/nerd-fonts

# Disable the newline at the start of the prompt
add_newline = true

# Overwrite a default_prompt_order and  use custom prompt_order
prompt_order=["conda", "username","hostname","python","directory", "git_branch", "time", "aws",  "memory_usage",  "line_break", "character"]

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[aws]
symbol = "  "
style = "dimmed bold blue"
displayed_items = "all"

[conda]
symbol = "conda::"
style = "dim green"
disabled = false

[directory]
truncation_length = 5
truncate_to_repo = false

[username]
disabled = false
show_always = true

[hostname]
ssh_only = true
prefix = "⟪"
suffix = "⟫"
trim_at = ".companyname.com"
disabled = false

[git_branch]
symbol = " "
truncation_length = 10
truncation_symbol = ""

[time]
disabled = false
format = "🕙[ %T ]"
utc_time_offset = -5
style = "yellow"

[line_break]
disabled = false

[python]
symbol = " "
pyenv_version_name = false
style = "bold dimmed yellow"

[memory_usage]
show_percentage = true
symbol = " "
style = "bold dimmed white"
threshold = 1
show_swap = false
disabled = false
